set(_AMENT_PACKAGE_NAME "serial_modbus_rtu_slavery")
set(serial_modbus_rtu_slavery_VERSION "1.0.0")
set(serial_modbus_rtu_slavery_MAINTAINER "nvidia <137196922@qq.com>")
set(serial_modbus_rtu_slavery_BUILD_DEPENDS "libmodbus" "rclcpp" "my_interfaces" "ament_index_cpp")
set(serial_modbus_rtu_slavery_BUILDTOOL_DEPENDS "ament_cmake")
set(serial_modbus_rtu_slavery_BUILD_EXPORT_DEPENDS "rclcpp" "my_interfaces" "ament_index_cpp")
set(serial_modbus_rtu_slavery_BUILDTOOL_EXPORT_DEPENDS )
set(serial_modbus_rtu_slavery_EXEC_DEPENDS "libmodbus" "rclcpp" "my_interfaces" "ament_index_cpp")
set(serial_modbus_rtu_slavery_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(serial_modbus_rtu_slavery_GROUP_DEPENDS )
set(serial_modbus_rtu_slavery_MEMBER_OF_GROUPS )
set(serial_modbus_rtu_slavery_DEPRECATED "")
set(serial_modbus_rtu_slavery_EXPORT_TAGS)
list(APPEND serial_modbus_rtu_slavery_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
